# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='grade',
            field=models.IntegerField(choices=[(0, '"전체관람가"'), (12, '"12세이상 관람가"'), (15, '"15세이상 관람가"'), (18, '"청소년 관람불가"')], default=1, help_text='관람 선택'),
        ),
    ]
